# Building Neural Networks in PyTorch

We will discuss how to build a machine learning algorithm with PyTorch, mainly focusing on two main classes:

- `torch.nn.Module`
- `torch.nn.Parameter`

These two classes contains the methods to call different types of layers and the parameters from these layers. The `torch.nn.Parameter` is a sub-class of the torch.Tensor class and registers the parameters in the objects of the Module class. The two classes, work together and make possible the building of a model. By observing the example below we can notice that models are built in two main phases:

- defining the type and the sequence of the layers (`init` method)
- defining how the output of each layer is fed forward across the network (`forward` method)

In the following example we will build a model by defining a class calles `Example_Model`, and we will implement 2 fully connected layers, the first followed by a ReLU activation function, and the second one from a Softmax function by using the `init` method. The `forward` method will also be defined to establish how the output of each layer will flow through the network.






In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
import torch

class Example_Model(torch.nn.Module):

    def __init__(self):
        super(Example_Model, self).__init__()

        self.linear1 = torch.nn.Linear(5, 10) # (5 in features, 10 out features)
        self.activation = torch.nn.ReLU()
        self.linear2 = torch.nn.Linear(10, 5) # (10 in features, 5 out features)
        self.softmax = torch.nn.Softmax()

    def forward(self, x):
        x = self.linear1(x)
        x = self.activation(x)
        x = self.linear2(x)
        x = self.softmax(x)
        return x

dummy_model = Example_Model()

We can print the model just by calling the instance `dummy_model` that we created:

In [3]:
print(dummy_model)

Example_Model(
  (linear1): Linear(in_features=5, out_features=10, bias=True)
  (activation): ReLU()
  (linear2): Linear(in_features=10, out_features=5, bias=True)
  (softmax): Softmax(dim=None)
)


In [4]:
from torchsummary import summary

summary(dummy_model)

Layer (type:depth-idx)                   Param #
├─Linear: 1-1                            60
├─ReLU: 1-2                              --
├─Linear: 1-3                            55
├─Softmax: 1-4                           --
Total params: 115
Trainable params: 115
Non-trainable params: 0


Layer (type:depth-idx)                   Param #
├─Linear: 1-1                            60
├─ReLU: 1-2                              --
├─Linear: 1-3                            55
├─Softmax: 1-4                           --
Total params: 115
Trainable params: 115
Non-trainable params: 0

We can print the details of a specific layer by calling the specific layer:

In [5]:
print(dummy_model.linear2)

Linear(in_features=10, out_features=5, bias=True)


We can print the parameters of the whole model, and we will have respectely a 

- 5x10 weight matrix for the first layer
- 10 bias parameters from the 1st layer
- 10x5 weight matrix for the first layer
- 5 bias parameters from the 1st layer

In [6]:
for param in dummy_model.parameters():
    print(param)

Parameter containing:
tensor([[ 0.3265,  0.0876, -0.2340, -0.1507, -0.2088],
        [-0.3483, -0.2962,  0.3250, -0.2340,  0.0179],
        [-0.1287, -0.0097,  0.4376,  0.1406,  0.3173],
        [ 0.1721,  0.1175,  0.0562, -0.0301,  0.2803],
        [-0.0160,  0.1330, -0.2040, -0.2861, -0.1951],
        [ 0.3858, -0.4261, -0.0258,  0.0161, -0.3093],
        [-0.2284,  0.2183,  0.0424, -0.3168, -0.1888],
        [ 0.2205,  0.2653,  0.1024,  0.0023, -0.2518],
        [ 0.1119,  0.4154, -0.0807, -0.0566,  0.3123],
        [-0.3263,  0.0473, -0.3313,  0.3113, -0.1327]], requires_grad=True)
Parameter containing:
tensor([ 0.3164, -0.1308, -0.0712,  0.1400,  0.0017, -0.1389,  0.3883, -0.2497,
         0.3083,  0.3729], requires_grad=True)
Parameter containing:
tensor([[ 0.2305,  0.0232, -0.2082,  0.2474, -0.2128, -0.0692, -0.2093,  0.2320,
          0.2549, -0.2258],
        [-0.0389, -0.0073, -0.2676, -0.0863, -0.1706, -0.0307,  0.0819,  0.1069,
          0.1141, -0.1011],
        [ 0.1174, 

We can print the parameters from a specific layer of our choice:

In [7]:
for param in dummy_model.linear2.parameters():
    print(param)

Parameter containing:
tensor([[ 0.2305,  0.0232, -0.2082,  0.2474, -0.2128, -0.0692, -0.2093,  0.2320,
          0.2549, -0.2258],
        [-0.0389, -0.0073, -0.2676, -0.0863, -0.1706, -0.0307,  0.0819,  0.1069,
          0.1141, -0.1011],
        [ 0.1174, -0.1820, -0.3103,  0.0081, -0.1000,  0.2045,  0.1277,  0.2375,
          0.1232,  0.0685],
        [-0.1838,  0.2427,  0.1553,  0.3095,  0.0345,  0.2310, -0.1493,  0.2479,
         -0.1499,  0.0968],
        [ 0.2249, -0.2928, -0.2919,  0.0759,  0.0650,  0.3080, -0.2481, -0.2310,
         -0.0951,  0.0938]], requires_grad=True)
Parameter containing:
tensor([-0.1397,  0.1226,  0.1450, -0.0347, -0.2238], requires_grad=True)
